<?php
namespace BasicDashboard\Foundations\Domain\EducationEligibleScores\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\EducationEligibleScores\EducationEligibleScore;


/**
 *
 * A EducationEligibleScoreRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface EducationEligibleScoreRepositoryInterface extends BaseRepositoryInterface
{
    public function filterEducationEligibleScore(array $params): Builder | EducationEligibleScore;
    public function getEducationEligibleScoreList($params): LengthAwarePaginator;
}