<?php

namespace BasicDashboard\Web\EducationEligibleScores\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\EducationEligibleScores\Services\EducationEligibleScoreService;
use BasicDashboard\Web\EducationEligibleScores\Validation\StoreEducationEligibleScoreRequest;
use BasicDashboard\Web\EducationEligibleScores\Validation\UpdateEducationEligibleScoreRequest;
use BasicDashboard\Web\EducationEligibleScores\Validation\DeleteEducationEligibleScoreRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A EducationEligibleScoreController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class EducationEligibleScoreController extends BaseController
{
    public function __construct(
        private EducationEligibleScoreService $educationEligibleScoreService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->educationEligibleScoreService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->educationEligibleScoreService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreEducationEligibleScoreRequest $request): RedirectResponse
    {
        return $this->educationEligibleScoreService->store($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->educationEligibleScoreService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->educationEligibleScoreService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateEducationEligibleScoreRequest $request, string $id): RedirectResponse
    {
        return $this->educationEligibleScoreService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteEducationEligibleScoreRequest $request): RedirectResponse
    {
        return $this->educationEligibleScoreService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
