<?php
namespace BasicDashboard\Foundations\Domain\MinimumEligibleScore\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\MinimumEligibleScore\MinimumEligibleScore;


/**
 *
 * A MinimumEligibleScoreRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface MinimumEligibleScoreRepositoryInterface extends BaseRepositoryInterface
{
    public function filterMinimumEligibleScore(array $params): Builder | MinimumEligibleScore;
    public function getMinimumEligibleScoreList($params): LengthAwarePaginator;
}