<?php

namespace BasicDashboard\Web\EducationEligibleScores\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A EducationEligibleScoreResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class EducationEligibleScoreResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            "exam_type"=>$this->exam_type,
            "margin_score"=>$this->margin_score,
            "eligible_score" => $this->eligible_score,
        ];
    }
}
