<?php
namespace BasicDashboard\Foundations\Domain\SingleEduEligibleMarks\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\SingleEduEligibleMarks\SingleEduEligibleMark;


/**
 *
 * A SingleEduEligibleMarkRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface SingleEduEligibleMarkRepositoryInterface extends BaseRepositoryInterface
{
    public function filterSingleEduEligibleMark(array $params): Builder | SingleEduEligibleMark;
    public function getSingleEduEligibleMarkList($params): LengthAwarePaginator;
}