<?php

namespace BasicDashboard\Foundations\Domain\MinimumEligibleScore;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


/**
 *
 * A MinimumEligibleScore is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
//#[ObservedBy([AuditObserver::class])]
class MinimumEligibleScore extends Model
{
    use HasFactory;
      //protected $table = 'table_name';
      protected $guarded = [

    ];

}
