<?php

namespace BasicDashboard\Foundations\Domain\EducationEligibleScores\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\EducationEligibleScores\Repositories\EducationEligibleScoreRepositoryInterface;
use BasicDashboard\Foundations\Domain\EducationEligibleScores\EducationEligibleScore;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A EducationEligibleScoreRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class EducationEligibleScoreRepository extends BaseRepository implements EducationEligibleScoreRepositoryInterface
{
    public function __construct(EducationEligibleScore $model)
    {
        parent::__construct($model);
    }

    public function filterEducationEligibleScore(array $params): Builder | EducationEligibleScore
    {
        $connection = $this->connection();
        if (isset($params['exam_type'])) {
            $connection = $connection->where('exam_type',$params['exam_type']);
        }
        return $connection;
    }

    public function getEducationEligibleScoreList($params): LengthAwarePaginator
    {
        return $this->filterEducationEligibleScore($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }
}
