<?php

namespace BasicDashboard\Web\SingleEduEligibleMarks\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\SingleEduEligibleMarks\Services\SingleEduEligibleMarkService;
use BasicDashboard\Web\SingleEduEligibleMarks\Validation\StoreSingleEduEligibleMarkRequest;
use BasicDashboard\Web\SingleEduEligibleMarks\Validation\UpdateSingleEduEligibleMarkRequest;
use BasicDashboard\Web\SingleEduEligibleMarks\Validation\DeleteSingleEduEligibleMarkRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A SingleEduEligibleMarkController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SingleEduEligibleMarkController extends BaseController
{
    public function __construct(
        private SingleEduEligibleMarkService $singleEduEligibleMarkService
    ) {
    }

    public function index(Request $request): View
    {
        return $this->singleEduEligibleMarkService->index($request->all());
    }

    public function edit(string $id): View | RedirectResponse
    {
        return $this->singleEduEligibleMarkService->edit($id);
    }

    public function update(UpdateSingleEduEligibleMarkRequest $request, string $id): RedirectResponse
    {
        return $this->singleEduEligibleMarkService->update($request->validated(), $id);
    }

    public function destroy(DeleteSingleEduEligibleMarkRequest $request): RedirectResponse
    {
        return $this->singleEduEligibleMarkService->destroy($request->validated());
    }
}
