<?php

namespace BasicDashboard\Web\SingleEduEligibleMarks\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A DeleteSingleEduEligibleMarkRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DeleteSingleEduEligibleMarkRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "id"=>"required",
        ];
    }
}
