<?php

namespace BasicDashboard\Web\SingleEduEligibleMarks\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateSingleEduEligibleMarkRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateSingleEduEligibleMarkRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "sub_1" => "nullable|numeric|min:0",
            "sub_2" => "nullable|numeric|min:0",
            "sub_3" => "nullable|numeric|min:0", 
            "sub_4" => "nullable|numeric|min:0",
            "sub_5" => "nullable|numeric|min:0",
            "sub_6" => "nullable|numeric|min:0"
        ];
    }

    protected function prepareForValidation()
    {
        $this->merge([
            'sub_1' => $this->sub_1 ?? 0,
            'sub_2' => $this->sub_2 ?? 0,
            'sub_3' => $this->sub_3 ?? 0,
            'sub_4' => $this->sub_4 ?? 0,
            'sub_5' => $this->sub_5 ?? 0,
            'sub_6' => $this->sub_6 ?? 0,
        ]);
    }
}
