<?php

namespace BasicDashboard\Web\EducationEligibleScores\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreEducationEligibleScoreRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreEducationEligibleScoreRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name"=>"required",
        ];
    }
}
