<?php

namespace BasicDashboard\Web\EducationEligibleScores\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateEducationEligibleScoreRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateEducationEligibleScoreRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "margin_score"=>"required|integer",
          "eligible_score"=>"required|integer"
        ];
    }
}
