<?php

namespace BasicDashboard\Foundations\Domain\MinimumEligibleScore\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\MinimumEligibleScore\Repositories\MinimumEligibleScoreRepositoryInterface;
use BasicDashboard\Foundations\Domain\MinimumEligibleScore\MinimumEligibleScore;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A MinimumEligibleScoreRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class MinimumEligibleScoreRepository extends BaseRepository implements MinimumEligibleScoreRepositoryInterface
{
    public function __construct(MinimumEligibleScore $model)
    {
        parent::__construct($model);
    }

    public function filterMinimumEligibleScore(array $params): Builder | MinimumEligibleScore
    {
        $connection = $this->connection();
        if (isset($params['keyword']) && strlen($params['keyword']) > 0) {
            $connection = $connection->where('name', 'LIKE', '%' . $params['keyword'] . '%');
        }
        return $connection;
    }

    public function getMinimumEligibleScoreList($params): LengthAwarePaginator
    {
        return $this->filterMinimumEligibleScore($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }
}
