<?php

namespace BasicDashboard\Web\MinimumEligibleScore\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A MinimumEligibleScoreResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class MinimumEligibleScoreResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            'min_education' => $this->min_education,
            'min_program' => $this->min_program,
            'min_activity' => $this->min_activity,
            'min_essay' => $this->min_essay,
            'min_mental' => $this->min_mental,
        ];
    }
}
