<?php

namespace BasicDashboard\Foundations\Domain\SingleEduEligibleMarks\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\SingleEduEligibleMarks\Repositories\SingleEduEligibleMarkRepositoryInterface;
use BasicDashboard\Foundations\Domain\SingleEduEligibleMarks\SingleEduEligibleMark;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A SingleEduEligibleMarkRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SingleEduEligibleMarkRepository extends BaseRepository implements SingleEduEligibleMarkRepositoryInterface
{
    public function __construct(SingleEduEligibleMark $model)
    {
        parent::__construct($model);
    }

    public function filterSingleEduEligibleMark(array $params): Builder | SingleEduEligibleMark
    {
        $connection = $this->connection();
        if (isset($params['keyword']) && strlen($params['keyword']) > 0) {
            $connection = $connection->where('name', 'LIKE', '%' . $params['keyword'] . '%');
        }
        return $connection;
    }

    public function getSingleEduEligibleMarkList($params): LengthAwarePaginator
    {
        return $this->filterSingleEduEligibleMark($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }
}
