<?php

namespace BasicDashboard\Web\Pages\Validation;

use Carbon\Carbon;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdatePageRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdatePageRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        \Log::info($this->all());
        return [
        //   "name"=>"required",
        ];
    }
    protected function passedValidation(): void
    {
        $this->merge([
            'date' => transform($this->date,fn() => Carbon::createFromFormat('m/d/Y', $this->date)->format('Y-m-d'))
        ]);
    }
}
