<?php

namespace BasicDashboard\Web\EducationEligibleScores\Services;

use BasicDashboard\Foundations\Domain\EducationEligibleScores\Repositories\EducationEligibleScoreRepositoryInterface;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\EducationEligibleScores\Resources\EducationEligibleScoreResource;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Exception;

/**
 *
 * A EducationEligibleScoreService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class EducationEligibleScoreService extends BaseController
{
    const VIEW = 'admin.educationEligibleScore';
    const ROUTE = 'educationEligibleScores';
    const LANG_PATH = "educationEligibleScore.educationEligibleScore";

    public function __construct(
        private EducationEligibleScoreRepositoryInterface $educationEligibleScoreRepositoryInterface,
    )
    {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): View
    {
        $educationEligibleScoreList = $this->educationEligibleScoreRepositoryInterface->getEducationEligibleScoreList($request);
        $educationEligibleScoreList = EducationEligibleScoreResource::collection($educationEligibleScoreList)->response()->getData(true);
        return $this->returnView(self::VIEW.".index", $educationEligibleScoreList, $request);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return view(self::VIEW.'.create');
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store($request): RedirectResponse
    {
        try {
            $this->educationEligibleScoreRepositoryInterface->beginTransaction();
            $this->educationEligibleScoreRepositoryInterface->insert($request);
            $this->educationEligibleScoreRepositoryInterface->commit();
            return $this->redirectRoute(self::ROUTE . ".index", __(self::LANG_PATH . '_created'));
        } catch (Exception $e) {
            return $this->redirectBackWithError($this->educationEligibleScoreRepositoryInterface, $e);
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        $educationEligibleScore = $this->educationEligibleScoreRepositoryInterface->edit($id);
        $educationEligibleScore = new EducationEligibleScoreResource($educationEligibleScore);
        $educationEligibleScore = $educationEligibleScore->response()->getData(true)['data'];
        return $this->returnView(self::VIEW . ".edit", $educationEligibleScore);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        $educationEligibleScore = $this->educationEligibleScoreRepositoryInterface->show($id);
        $educationEligibleScore = new EducationEligibleScoreResource($educationEligibleScore);
        $educationEligibleScore = $educationEligibleScore->response()->getData(true)['data'];
        return $this->returnView(self::VIEW . '.show', $educationEligibleScore);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update($request, string $id): RedirectResponse
    {
         try {
            $this->educationEligibleScoreRepositoryInterface->beginTransaction();
            $this->educationEligibleScoreRepositoryInterface->update($request, $id);
            $this->educationEligibleScoreRepositoryInterface->commit();
            return $this->redirectRoute(self::ROUTE . ".index", __(self::LANG_PATH . '_updated'));
        } catch (Exception $e) {
            return $this->redirectBackWithError($this->educationEligibleScoreRepositoryInterface, $e);
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy($request): RedirectResponse
    {
         try {
            $this->educationEligibleScoreRepositoryInterface->beginTransaction();
            $this->educationEligibleScoreRepositoryInterface->delete($request['id']);
            $this->educationEligibleScoreRepositoryInterface->commit();
            return $this->redirectRoute(self::ROUTE . ".index", __(self::LANG_PATH . '_deleted'));
        } catch (Exception $e) {
            return $this->redirectBackWithError($this->educationEligibleScoreRepositoryInterface, $e);
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
