<?php

namespace BasicDashboard\Web\SingleEduEligibleMarks\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A SingleEduEligibleMarkResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SingleEduEligibleMarkResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            "exam_type" =>$this->exam_type,
            "sub_1"=>$this->sub_1,
            "sub_2"=>$this->sub_2,
            "sub_3"=>$this->sub_3,
            "sub_4"=>$this->sub_4,
            "sub_5"=>$this->sub_5,
            "sub_6"=>$this->sub_6,
        ];
    }
}
