<?php

namespace BasicDashboard\Web\Pages\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A PageResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageResource extends JsonResource
{
    public function toArray($request):array
    {
        $this['thumbnail'] ??= '/Default/default_article_pic.jpg';
        return [
            "id" =>customEncoder($this->id),
            "title"=>$this->title,
            'title_other' => $this->title_other,
            "slug" => $this->slug,
            "type" => $this->type,
            'description' => $this->description,
            "description_other"=>$this->description_other,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            'createdBy' => $this->createdBy->name,
            'writtenBy' => $this->writtenBy->name,
            "is_published"=>$this->is_published,
            "is_banner"=>$this->is_banner,
            "is_highlighed"=>$this->is_highlighed,
            "date"=>$this->date ? date('m/d/Y', strtotime($this->date)) : null,
            "link" => retrievePublicFiles($this->link),
        ];
    }
}
