<?php

namespace BasicDashboard\Web\MinimumEligibleScore\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateMinimumEligibleScoreRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateMinimumEligibleScoreRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'min_education' => 'required',
            'min_program' => 'required',
            'min_activity' => 'required',
            'min_essay' => 'required',
            'min_mental' => 'required',
        ];
    }
}
