<?php

namespace BasicDashboard\Web\ApplicantRecord\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ApplicantRecordResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ApplicantRecordIndexResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" => $this->id,
            "applicant_sr" => $this->applicant_sr,
            "mesid" => $this->mesid,
            "email" => $this->email,
            "current_school" => $this->current_school,
            "additional_data1" => $this->additional_data1,
            "additional_data2" => $this->additional_data2,
            "exam_type" => $this->exam_type,
            "essay_score" => $this->essay_score,
            "mental_score" => $this->mental_score,
            "activity_type" => $this->activity_type,
            "education_score" => $this->education_score,
            "sub_1" => $this->sub_1,
            "sub_2" => $this->sub_2,
            "sub_3" => $this->sub_3,
            "sub_4" => $this->sub_4,
            "sub_5" => $this->sub_5,
            "sub_6" => $this->sub_6,
            "education_eligible" => $this->education_eligible,
            "essay_eligible" => $this->essay_eligible,
            "mental_eligible" => $this->mental_eligible,
            "activity_eligible" => $this->activity_eligible,
            "program_eligible" => $this->program_eligible,
            "total_scores" => $this->total_scores,
            "final_eligibility" => $this->final_eligibility,
            "manual_eligible" => $this->manual_eligible,
            "month" => $this->month,
            "activity_score" => $this->activity_score,
            "program_score" => $this->program_score,
            "total_edu_marks" => $this->total_edu_marks,
        ];
    }
}
